Feature/191 writing guide animation
TeamChaRo/ChaRo-iOS pull request #192
Opened 2022-03-06 18:09 UTC by hryeong66

## 📌 관련 이슈

-  close: #191 

## 📌 변경 사항 및 이유

지도 작성하기 처음 들어왔을 떄 안내문구 보여주는 애니메이션 구혔습니다. 
애니메이션이 디자이너가 원한게 맞는지랑 지속 시간 등 디테일은 디자인 팀과 논의해서 조금 바뀔수도 있습니다.

## 📌 PR Point

일회성 애니메이션이라서 한 함수 안에서 지역 변수로 다 처리했습니다!
```swift
func setupGuideAnimationView(){
        if !isFirstOpen {return}
        let backgroundView = UIView()
        backgroundView.backgroundColor = .mainBlack.withAlphaComponent(0.8)
        let imageView = UIImageView(image: ImageLiterals.imgMapFirstGuide)
        view.addSubview(backgroundView)
        backgroundView.snp.makeConstraints{
            $0.top.equalTo(tableView.snp.bottom)
            $0.leading.trailing.bottom.equalToSuperview()
            
        }
        backgroundView.addSubview(imageView)
        imageView.snp.makeConstraints{
            $0.top.equalToSuperview().inset(225)
            $0.leading.equalToSuperview().inset(18)
            $0.trailing.equalToSuperview().inset(22)
        }
        animator.addAnimations {
            backgroundView.alpha = 0
            imageView.alpha = 0
        }
        animator.startAnimation()
        isFirstOpen = false
    }
--------------------------------------------------
// 이코드 중에서 animator 부분 분리
private func startGuideAnimation(view: UIView, image: UIImageView){
    animator.addAnimations {
            view.alpha = 0
            image.alpha = 0
        }
     animator.startAnimation()
}

```

아래에 적어놓은 애니메이션 부분을 함수로 나눴다가
이 함수가 재사용될 일이 없고, 파라미터로 넘겨주는게 더 비효율적이지 않을까?라는 생각이 들어서
한 함수 안에서 했습니다! 어떤 코드가 더 좋을까요?

## 📌 참고 사항

![Simulator Screen Recording - iPhone 13 - 2022-03-07 at 02 56 23](https://user-images.githubusercontent.com/59547116/156935742-01b3b5b7-af66-4c37-a2a4-fce67aad3d48.gif)

2022-03-13 14:40 UTC, inddoni requested changes
보니까 중간에 이미지에 텍스트가 포함되어있던데, 텍스트는 따로 만들어서 넣는게 낫지 않을까 하는 의견을 드려봅니당 🥕  전에 텍스트 이미지를 넣었더니 비율을 맞춰도 찌그러지거나 약간 부자연스럽더라구요 ㅠㅠ

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +    private lazy var tableView = UITableView().then{
```suggestion
    private lazy var tableView = UITableView().then {
```
전체적으로 then 뒤에 스페이스가 있으면 좋을 것 같아요~

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>      public func setAddressModel(model: AddressDataModel, cellType: String, index: Int){
P5; 마크업을 컨벤션으로 정하진 않았던 것 같은데 통일성있으면 더 좋을 것 같아서 한번 이야기 해봐도 좋을 것 같아요!

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
> +    private var backButton = UIButton().then{
```suggestion
    private var backButton = UIButton().then {
```
요기 커밋에서도 then 뒤에 스페이스 확인부탁해용

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +    private var isFirstOpen = true
```suggestion
    private var isFirstOpen: Bool = true
```

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        if !isFirstOpen {return}
P2; early exit 하는 부분은 guard 문으로 하는게 가독성측면에서 더 좋지 않을까요?
```suggestion
        guard isFirstOpen else { return }
```

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
요 메서드에서는 레이아웃 부분은 분리해도 좋을 것 같아요. 애니메이션 동작을 위주로 구성되면 더 좋을 것 같아요!

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
> +        guard let addressMainVC = navigationController?.viewControllers[endIndex-3] as? AddressMainVC else {return}
P5; 리턴 사이 간격을 조금 떼어주고 시퍼요 😉 `{ return }`

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>                                                  cellType: SearchKeywordCell.self)){ row, element, cell in
굳 좋네영

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>                  self.viewModel.findAutoCompleteAddressList(keyword: $0 ?? "")
오엥 디버깅 print 문이 커밋됐네용

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
> +}
요거 클래스 내부에 넣어도 되지 않을까요? 따로 밖으로 뺀 이유가 있을까용

2022-03-13 14:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
>      public var address = AddressDataModel()
특정 셀에는 final 키워드를 붙이는게 좋을 것 같아요

2022-03-13 14:42 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>      public func setAddressModel(model: AddressDataModel, cellType: String, index: Int){
- //MARK: - something
- // MARK: - something
- //MARK: something
- // MARK: something
부터 시작해서 어떤 걸 마크업 할건지 이야기해보고 싶네용~~

2022-03-14 13:07 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>      public func setAddressModel(model: AddressDataModel, cellType: String, index: Int){
넵 한번 논의하고 다 같이 맞추는게 좋을 것 같네요!

2022-03-14 13:07 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        if !isFirstOpen {return}
오호 이게 더 깔끔하네요! 반영하겠습니다ㅎㅎ

2022-03-14 13:09 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
이 부분이 고민이 된다고 이야기한 부분입니다! 
이 함수 내부에서만 사용하는 backgroundview, imageView가 있는데
애니메이션 부분을 분리하면 파라미터로 해당 view들을 받아야 해서 고민이 들었어요
함수는 분리하는게 좋겠죠?

2022-03-14 13:10 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
> +        guard let addressMainVC = navigationController?.viewControllers[endIndex-3] as? AddressMainVC else {return}
넵 반영할게요!

2022-03-14 13:10 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
>                  self.viewModel.findAutoCompleteAddressList(keyword: $0 ?? "")
삭제할게요!

2022-03-14 13:10 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
>      public var address = AddressDataModel()
넵 반영하겠습니다~!

2022-03-14 13:37 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +    private lazy var tableView = UITableView().then{
반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/879a94e089f395af987f7355296c71fd3219dfa4

2022-03-14 13:37 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
> +    private var backButton = UIButton().then{
반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/879a94e089f395af987f7355296c71fd3219dfa4

2022-03-14 13:38 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
> +        guard let addressMainVC = navigationController?.viewControllers[endIndex-3] as? AddressMainVC else {return}
반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/c572f18d2fae61a5a1ba160be89fb2c671bd29db

2022-03-14 13:39 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
> +}
처음에는 다른 VC에서도 사용해서 빼놓긴 했었는데 사용하는 부분이 한군데 밖에 없어서 클래스 내부로 넣었습니다! 감사합니다😘

반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/911da0e3610af78cdef7bfeb97cd5fa38707173a

2022-03-14 13:41 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        if !isFirstOpen {return}
반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/911da0e3610af78cdef7bfeb97cd5fa38707173a

2022-03-14 13:41 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +    private var isFirstOpen = true
반영했습니다 :) https://github.com/TeamChaRo/ChaRo-iOS/pull/192/commits/4e180e961fb6fcbe98b1f662daddbf757b1e1bff

2022-03-15 13:40 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
뷰 자체를 이 메서드 안에서 만드는 이유가 있을까요?

2022-03-15 13:41 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
매모리 문제 때문이라면 lazy 하게 선언해두고 메서드 내부에서는 애니메이션만 다루는게 좋지 않을까하는 생각이에요!

2022-03-15 17:25 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
> 뷰 자체를 이 메서드 안에서 만드는 이유가 있을까요?
제일 처음 작성하기 지도 VC가 load 되었을 떄, 안내용으로 보여지는 애니메이션 입니다!
일회성으로 사용하는 뷰들이기 때문에 VC가 해당 프로퍼티들을 가지고 있을 필요가 없다고 생각했고
해당 함수가 끝나면 뷰들이 사라지는게 낫지 않을까? 했습니다!

인정님과 이야기하면서 생각난건데 저 부분 자체를 conponent로 빼고
사용할때만 addSubview로 넣고 
애니메이션이 끝나면 remove 해주는 식으로 해도 찮을 것 같네요!

2022-03-16 18:13 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
> +        }
오 위 내용 좋네요! 잠깐 보여지는 뷰라 함수에서 만드는 것 보다 명시적으로 만들고, remove 하는 방식이 더 좋아보여요! 요것만 반영해주시면 될 것 같고 기능상에 문제는 없어서 어프룹 해둘게요~

2022-03-16 18:14 UTC, inddoni approved these changes

2022-03-17 09:41 UTC, merged