[FEAT] 게시물 상세보기 디자인 변경 사항 적용
TeamChaRo/ChaRo-iOS pull request #197
Opened 2022-03-15 17:17 UTC by hryeong66

## 📌 관련 이슈

-  close: #196 

## 📌 변경 사항 및 이유

게시물 상세보기 디자인 변경 사항 적용했습니다!
디자인 적용하고 보니까 아직 여기서 해야할 일들이 좀 많더라고요..
스크랩이랑 좋아요 공유하기는 다른 이슈 파서 수정하겠습니다!

뿌듯한 점 하나는 이전에는 cell row height를 하나하나 다 지정했었는데
지금은 cell에서 크기를 계산할 수 있도록 해서 따로 cell row height를 지정하지 않아도 됩니다!🤩

IBOutlet으로 잡아놓았던 UI 모두 코드로 변경했습니다. 
component로 사용할 수 있는 부분은 최대한 살릴려고 해봤습니다
보시다가 좋은 아이디어 있으면 적극적으로 이야기해주세요😉

## 📌 PR Point

제가 만들었던 코드도 뒤죽박죽인 느낌이 강해서 Base코드들을 사용하는거에 대해서 어떻게 생각하시나요??
그리고 viewModel 의존성을 주입하는 부분이 너무 모호해서 coordinator를 도입하면 어떨까요?

## 📌 참고 사항

![Simulator Screen Recording - iPhone 13 - 2022-03-16 at 02 07 36](https://user-images.githubusercontent.com/59547116/158433296-d45f2df2-bd0b-453c-b075-f0e6af7dca79.gif)

2022-03-16 18:15 UTC, inddoni commented
엄청난 빅 PR이네요,,? 약 4000라인에 68개 커밋 ㅠㅠ 나눌 수 있는 부분은 나누어 올렸다면 더 좋았겠네요

2022-03-16 18:17 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIView+.swift
> +        toastLabel.clipsToBounds = true
요런 부분에도 then을 적용하면 좋을 것 같아요~

2022-03-16 18:31 UTC, inddoni requested changes
뭔가 이전 PR과 겹치는 커밋이 있는 것 같은데 이전 PR과 이어지는거라면 base를 develop이 아닌 이전 PR 로 연결해주시면 좋아요~ (전 PR이 머지되면 자동으로 base가 전 PR의 base 였던 develop으로 바뀌어요)

겹치는 게 있는 것 같아서 제대로 못 본 부분이 있는데 수정 해주시면 다시 볼게요!

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
> +    init(postId: Int){
```suggestion
    init(postId: Int) {
```

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
> +    struct Input{
```suggestion
    struct Input {
```

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
> +    struct Output{
```suggestion
    struct Output {
```

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
> +    struct Output{
등등 요 파일 전체적으로 스타일 확인 부탁드릴게요~

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
> +                if let data =  resultData as? PostDetailData{
```suggestion
                if let data = resultData as? PostDetailData{
```
whitespace가 들어갔어요~

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Extensions/UICollectionView+.swift
> +            fatalError("Could not dequeue cell with identifier: \(T.className)")
fatalError는 호출 시 크래시를 발생시키는데, 그릴 cell이 없을 때 크래시를 발생시키는 건 좋은 경험이 아닐 것 같아요. 에러를 안내하는 건 `assertionFailure("")` 로 디버깅 모드에서만 확인하고, 프로덕션에는 영향을 끼치지 않도록 하는 것이 좋을 것 같아요~ (그리고 fatal Error를 남용하는 것이 리젝 사유가 될 수 있다고 알고 있어요)

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
> +        print("여기 잘 눌림?")
테스트 프린트문이 포함됐어요~

2022-03-16 18:31 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
> +    var titleLabel = UILabel().then {
내부에서만 사용한다면 private를 붙여주세요!

2022-03-25 09:02 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
> +    var titleLabel = UILabel().then {
이부분은 외부에서 접근해서 사용해서 private 안붙였습니다😊

2022-03-25 09:03 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
> +        print("여기 잘 눌림?")
어메 삭제했습니다~! https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/915c1cf0f6b55c30ed3b1665ef7e7a4464f47d15

2022-03-25 09:03 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIView+.swift
> +        toastLabel.clipsToBounds = true
적용했습니다~! https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/915c1cf0f6b55c30ed3b1665ef7e7a4464f47d15

2022-03-25 11:35 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Extensions/UICollectionView+.swift
> +            fatalError("Could not dequeue cell with identifier: \(T.className)")
@inddoni 
오 깊게 생각하지 못했던 부분이라서 알려줘서 감사해요😊
근데 이부분을 print로 바꾸면 이렇게 해야할 것 같은데 이게 더 나은가요??

```swift 
func dequeueReusableCell<T: UICollectionViewCell>(forIndexPath indexPath: IndexPath) -> T {
        guard let cell = self.dequeueReusableCell(withReuseIdentifier: T.className,
                                                  for: indexPath) as? T else {
            print("DEBUG: Could not find cell with reuseID \(T.className)")
            return T()
            //fatalError("Could not find cell with reuseID \(T.className)")
        }
        return cell
    }
```

2022-03-27 09:09 UTC, inddoni approved these changes

2022-03-27 09:09 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeTodayDriveTVC.swift
> +        //postDelegate?.sendPostID(data: postid)
요고는 머에용?

2022-03-27 09:09 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostAttentionTVC.swift
> +        if list.count != 4 { return }
```suggestion
        guard list.count >= 4 else { return }
```
guard 문이 더 명시적일 것 같아요. 

이건 옵셔널인데,, 조건이 조금 불안정하긴한데 list를 count를 체크하는 것 말고 인덱스를 검증하는 방법은 어떨까요?

2022-03-27 09:09 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostCourseThemeTVC.swift
> +        if themeStackView.arrangedSubviews.count == 3 { return }
early exit은 guard로 가는게 더 명시적일 것 같은데 어떻게 생각하시나요~?

2022-03-27 09:09 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoTVC.swift
> +        layout.scrollDirection = .horizontal
요것도 then 적용할 수 있지 않을까요?

2022-03-27 09:32 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeTodayDriveTVC.swift
> +        //postDelegate?.sendPostID(data: postid)
요 부분은 테스트 때문에 주석처리 했었는데 방금 삭제했습니다! https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/a32331625a35ec0cc29858c5cd7a3d6f37a9e071

2022-03-27 09:33 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostCourseThemeTVC.swift
> +        if themeStackView.arrangedSubviews.count == 3 { return }
오오 guard 문이 더 좋은 것 같네요! 변경했습니다😊
https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/a32331625a35ec0cc29858c5cd7a3d6f37a9e071

2022-03-27 09:33 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoTVC.swift
> +        layout.scrollDirection = .horizontal
넵~ 적용했습니다 https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/a32331625a35ec0cc29858c5cd7a3d6f37a9e071

2022-03-27 09:35 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostAttentionTVC.swift
> +        if list.count != 4 { return }
guard로 변경했어요~! https://github.com/TeamChaRo/ChaRo-iOS/pull/197/commits/a32331625a35ec0cc29858c5cd7a3d6f37a9e071

@inddoni 인덱스를 검증한다는게 잘 와닿지 않아서 혹시 생각한게 있으면 얘기해 줄 수 있을까요??😊

2022-03-27 17:33 UTC, merged