[FEAT] #153 비밀번호 수정 구현 완료
TeamChaRo/ChaRo-iOS pull request #201
Opened 2022-03-25 07:19 UTC by comeheredart

## 📌 관련 이슈

  

## 📌 변경 사항 및 이유

비밀번호 수정 기능 서버 연결까지 구현했습니다.

## 📌 PR Point

예전에 만들어두었던 비밀번호 뷰가 있어서 재활용했습니다.

## 📌 참고 사항

우선 로그인 UserDefault 로직이 정리가 안되어서 기존 비밀번호는 '12345' 로 설정해야 새 비번 입력창이 나타납니다.
-> 수정 예정입니당!

2022-03-29 06:42 UTC, hwangJi-dev requested changes
설정뷰 기능까지 도와주셔서 감사합니다 ,, >< 코드리뷰 한번만 봐주시구 코멘트 달아주세용!!

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
>                      guard let statusCode = dataResponse.response?.statusCode else {return}
요기 {return} 부분 Swift 기본 스타일 가이드에 맞춰 { return } 으로 수정하는거 어떨까요 ~?

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Models/ThemeDataModel.swift
>  }
data 부분이 Drive형 모델로 바뀌었는데 TotalDrive 모델이 살아있는 이유가 있나요~ ? (잘 몰라가지고 궁금해서!)

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostAllTVC.swift
>              let element = selectedDriveList[indexPath.row]
오 요소 변수화 좋네요!

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangePasswordVC.swift
> +    static let identifier = "ChangePasswordVC"
이부분 지우고 ChangePasswordVC 불러오는 부분에서 `ChangePasswordVC.className`으로 불러오는걸로 수정해도 좋을 것 같아요!!🤗

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
> +        }
case 2만 사용하고 나머지는 다 break니까 case 0,1에 대한 분기처리 지우고 default문으로 통일해도 좋을 것 같아요!!
여기서도 ChangeImageVC.className 사용하면 identifier 코드 지울 수 있을 것 같아욤!!

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangeImageVC.swift
> +        print("왈왈")
ㅋㅋㅋㅋㅋ 프린트 왈왈

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangeImageVC.swift
>          actionsheetController.addAction(actionCancel)
actionSheet 함수 UIViewController+에 없는 것 같은데 시간 되면 extension으로 빼서 다른 사람들도 사용할 수 있도록 만들어놓는 것도 좋을 것 같아요~ 나중에! ㅎㅋㅎㅋ (다른데도 사용되는 데가 있다면 🤗 )

2022-03-29 06:42 UTC, hwangJi-dev commented on ChaRo-iOS/ChaRo-iOS/Source/Services/UpdatePasswordService.swift
> +
요런 불필요한 공백들 지우면 더 좋을 것 같아요오오🤗

2022-03-29 10:38 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
>                      guard let statusCode = dataResponse.response?.statusCode else {return}
악 저런게 숨어있었네효 ~~~

2022-03-29 11:19 UTC, hryeong66 reviewed
고생하셨어요~! 💕
지은님이 코드리뷰 해준 부분과 더해서
PasswordView.swift 이 파일에 옵셔널 부분이 모두 강제 언래핑되어 있어서
이부분도 같이 수정해주실 수 있을까요~??😃

2022-03-29 13:18 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Models/ThemeDataModel.swift
>  }
오 지금 보니까 예전에는 배열 하나로 들어오던 데이터가 하나씩 넘어오는 것 같아서 필요없는 것 같아요! 
매의 눈 지은 ~

2022-03-29 13:19 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostAllTVC.swift
>              let element = selectedDriveList[indexPath.row]
칭찬은 고래를 춤추게 한다.

2022-03-29 13:30 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangePasswordVC.swift
> +    static let identifier = "ChangePasswordVC"
오 그런 방법두 있었군뇨!! 맨날 identifier 만들어서 썼는데 ,,, 광광

2022-03-29 13:35 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
> +        }
왕 무지성으로 쓴 거 티나내요,,, 지은쨩 감사!!!!!!

2022-03-29 14:51 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangeImageVC.swift
> +        print("왈왈")
아쉽지만 더 이상은 볼 수 없습니다.

2022-03-29 14:52 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangeImageVC.swift
>          actionsheetController.addAction(actionCancel)
오 진짜 좋은생각! 안그래도 프로필 수정에서 쓰여서 만들어보겠슴니당!!

2022-03-29 14:54 UTC, comeheredart commented on ChaRo-iOS/ChaRo-iOS/Source/Services/UpdatePasswordService.swift
> +
수정갈겻슴니당!!

2022-04-02 14:50 UTC, inddoni approved these changes
전체적으로 print 문으로 테스트한 부분을 지우거나 (다 사용한거라면) 로그를 찍을 용도면 debugPrint나 log로 수정되면 좋을 것 같아요~ 그 외에는 지은, 혜령이가 잘 봐줘서 좋네용!

2022-04-12 18:19 UTC, merged