[BUG] 홈 네비게이션에 차로 로고 안나오는 증상 수정 및 디자인 변경
TeamChaRo/ChaRo-iOS pull request #211
Opened 2022-04-16 14:06 UTC by parkikbum

## 📌 관련 이슈

closed: #208 
  

## 📌 변경 사항 및 이유

이부분이 아직 이미지 리터럴로 수정 전이길래 수정하였고, 
이제 네비게이션바에 섀도우가 안들어가고 선으로 하나만 들어가서 이부분도 수정하였습니다. 

## 📌 PR Point

## 📌 참고 사항

여기가 지원누나랑 코드가 겹치는 부분이 많아서.. 좀 상의를 ,, 해봐야될거같아요,,

https://user-images.githubusercontent.com/73978827/163677959-07d22a2e-21b6-4041-a1a8-ba43a637f61f.MP4

2022-04-16 14:28 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
> +    }
하나의 함수에서 관리하는 건 어떤가요?
```
private func configureLogoImage(isWhite: Bool) {
  let logoImage: UIImage
  if isWhite {
    logoImage = ImageLiterals.icCharoLogoWhite 
  } else {
    logoImage = ImageLiterals.icSearchBlack
  // 홈 네비게이션 처리
}
```

2022-04-16 14:29 UTC, inddoni requested changes
파라미터로 받아서 하나의 함수에서 처리하는 방향으로 개선되어도 좋을 것 같아요~
그리고 로고 이미지는 여기서만 쓰이니까 private로 수정부탁드려요!

2022-04-17 13:50 UTC, parkikbum commented on ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
> +    }
넵 ! 완료했습니다!
b7bdfff54208b461db8f223a102823c59fe78b25

2022-04-17 14:49 UTC, inddoni approved these changes
빠른수정 최고다!!!!!

2022-04-18 12:00 UTC, merged