[]
TeamChaRo/ChaRo-iOS pull request #215
Opened 2022-04-19 12:55 UTC by hryeong66

## 📌 관련 이슈

  

## 📌 변경 사항 및 이유

## 📌 PR Point

## 📌 참고 사항

2022-05-05 14:24 UTC, inddoni requested changes
깔끔해졌네요~~

2022-05-05 14:24 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/AddressMainViewModel.swift
> +    func postSearchKeywords() {
외부에서도 사용하게 되었나요? private가 지워졌길래요!

2022-05-05 14:24 UTC, inddoni commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
> +    func setContent(element: AddressDataModel, keyword: String, date: String) {
요것도 private가 되면 좋을 것 같아요!

2022-06-07 09:20 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/ViewModels/AddressMainViewModel.swift
> +    func postSearchKeywords() {
넵! 해당 viewModel에 정의된 이 함수를 AddressMainVC가 호출을 해야해서 private을 뺐습니다~!

2022-06-07 09:21 UTC, hryeong66 commented on ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
> +    func setContent(element: AddressDataModel, keyword: String, date: String) {
요것도 외부에서 접근해서 사용하려고 private 뺐습니다 :)

2022-06-07 09:26 UTC, hwangJi-dev approved these changes
흠잡을데가 없네요. 어푸룹 드립니다.

2022-06-07 10:40 UTC, inddoni approved these changes
잘 봤어요~~ 짝짝

2022-06-07 10:40 UTC, merged